name: Deploy Streamlit app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set environment variable for API key
      env:
        API_KEY_OPENWEATHERMAPS: ${{ secrets.API_KEY_OPENWEATHERMAPS }}
      run: echo "API_KEY_OPENWEATHERMAPS=${API_KEY_OPENWEATHERMAPS}" >> $GITHUB_ENV

    - name: Run Streamlit app
      env:
        API_KEY_OPENWEATHERMAPS: ${{ secrets.API_KEY_OPENWEATHERMAPS }}
      run: streamlit run app.py
